# the Julia programming language
<img src="https://i1.wp.com/www.numfocus.org/wp-content/uploads/2016/07/julia-logo-300.png?w=1080&ssl=1" alt="Julia logo" width="100"/>
So, why Julia?

* free, open-source
* high-level, thus easy to use
* expressive, read-like-a-book syntax
* fast (design choices allow just-in-time compiler to make optimizations, resulting in fast code)
* safety (offers optional type assertion)
* designed especially for scientific computing
* easy parallelization across cores
* multiple dispatch (we'll see later)

[link to official Julia website](https://julialang.org/) and [its documentation](https://docs.julialang.org/en/v1/)

[link to recent Nature article on Julia](https://www.nature.com/articles/d41586-019-02310-3)

another great resource to learn more Julia: [Julia express](http://bogumilkaminski.pl/files/julia_express.pdf)

## hello world, assignment

"an assignment statement sets and/or re-sets the value stored in the storage location(s) denoted by a variable name; in other words, it copies a value into the variable" - [Wikipedia](https://en.wikipedia.org/wiki/Assignment_(computer_science))

In [1]:
x = 5.3 # not "x equals 5.3" but, "assign x to be 5.3"

5.3

assignment is not the same as "equals"! read [here](https://en.wikipedia.org/wiki/Assignment_(computer_science)#Assignment_versus_equality).

In [2]:
x == 5.3

true

In [3]:
println("hello, world!") # "ln" is for "line" to creat a new line afterwards.

hello, world!


In [4]:
println("what's x? ", x)

what's x? 5.3


## types

`x` is represented on your computer using a chuck of memory consisting of 64 bits (bit = binary digit). It is represented in the [double-precision floating point format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).

<img src="https://upload.wikimedia.org/wikipedia/commons/a/a9/IEEE_754_Double_Floating_Point_Format.svg" alt="bits" width="500"/>

In [5]:
typeof(x)

Float64

In [6]:
y = 5
typeof(y)

Int64

In [7]:
my_name = "Cory"
typeof(my_name)

String

the `Symbol` is an [interned string](https://en.wikipedia.org/wiki/String_interning), which makes e.g. string comparison operations faster. 

For those interested:
A more nuanced view of the `Symbol` is [here](https://stackoverflow.com/questions/23480722/what-is-a-symbol-in-julia#) by the co-creator and core developer of Julia. The function `pointer_from_objref` in Julia allows you to see where in memory an object in Julia is stored. Experiment with a `Symbol` and `String` to illustrate that `Symbol`s are *interned* strings.

In [8]:
my_name = :Cory
typeof(my_name)

Symbol

In [9]:
typeof(true)
typeof(false)

Bool

## dictionaries
a collection of (key, value) pairs. e.g. key = element, value = atomic mass

constructing a dictionary

In [10]:
atomic_mass = Dict{Symbol, Float64}(:C => 12.01, :N => 14.0067, :O => 15.999, :H => 1.01)

Dict{Symbol,Float64} with 4 entries:
  :N => 14.0067
  :H => 1.01
  :O => 15.999
  :C => 12.01

note the order is not the same as when we constructed the dictionary... so never assume the dictionary is in a certain order. for ordered elements just use an `Array`

querying a dictionary via passing the key, returning the value

In [11]:
atomic_mass[:C]

12.01

add a (key, value) pair to a dictionary

In [12]:
atomic_mass[:H] = 1.008
atomic_mass

Dict{Symbol,Float64} with 4 entries:
  :N => 14.0067
  :H => 1.008
  :O => 15.999
  :C => 12.01

iterate through a dictionary

In [13]:
for (element, mass) in atomic_mass # iterate over, unpack the (key, value) pairs
    print("the atomic mass of ")
    print(element)
    println(" is ", mass)
end

the atomic mass of N is 14.0067
the atomic mass of H is 1.008
the atomic mass of O is 15.999
the atomic mass of C is 12.01


what are the keys? what are the values?

In [14]:
keys(atomic_mass)

Base.KeySet for a Dict{Symbol,Float64} with 4 entries. Keys:
  :N
  :H
  :O
  :C

In [15]:
values(atomic_mass)

Base.ValueIterator for a Dict{Symbol,Float64} with 4 entries. Values:
  14.0067
  1.008
  15.999
  12.01

## arrays

In [16]:
x = [6.3, 1.2, 8.2, 10.8] # column vector

4-element Array{Float64,1}:
  6.3
  1.2
  8.2
 10.8

### changing an element

In [17]:
x[3] = 43.0
x

4-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8

### iterating through an array

In [18]:
# (1) iterating through indices of the array 1,2,...,length(x)
for i = 1:length(x)
    println("x[$i] = ", x[i])
end

# (2) directly iterating through the elements
println("entries are: ")
for x_i in x
    println("  ", x_i)
end

# (3) iterating through both the indices and the elements
for (i, x_i) in enumerate(x)
    println("x[$i] = $x_i")
end

x[1] = 6.3
x[2] = 1.2
x[3] = 43.0
x[4] = 10.8
entries are: 
  6.3
  1.2
  43.0
  10.8
x[1] = 6.3
x[2] = 1.2
x[3] = 43.0
x[4] = 10.8


### adding elements to an array
... to the end

In [19]:
push!(x, 23.0) # exlamation means function will modify its argument
x

5-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8
 23.0

... to the beginning

In [20]:
pushfirst!(x, 0.0)
x

6-element Array{Float64,1}:
  0.0
  6.3
  1.2
 43.0
 10.8
 23.0

### slicing 

#### by indices (by `Array`s of `Int64`s)

In [21]:
ids_i_want = [2, 6]

println("x = ", x)
println("x[ids_i_want] = ", x[ids_i_want])

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[ids_i_want] = [6.3, 23.0]


In [22]:
x[2:3]

2-element Array{Float64,1}:
 6.3
 1.2

In [23]:
x[2:end]

5-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8
 23.0

#### by specifying whether or not (`true`/`false`) we want to keep each element (by `Array`s of `Bool`s)

In [24]:
keep_entry = [true, false, false, false, false, true]

println("x = ", x)
println("x[keep_entry] = ", x[keep_entry])

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[keep_entry] = [0.0, 23.0]


this way of slicing is especially useful for selecting certain elements of an array that obey a certain condition

e.g., let's get all array elements that are greater than 12.

In [25]:
x > 12.0 # "is this vector greater than this number?" makes no sense.

MethodError: MethodError: no method matching isless(::Float64, ::Array{Float64,1})
Closest candidates are:
  isless(::Float64, !Matched::Float64) at float.jl:459
  isless(!Matched::Missing, ::Any) at missing.jl:66
  isless(::AbstractFloat, !Matched::AbstractFloat) at operators.jl:156
  ...

precede comparison `>` with a `.` to indicate "we are doing this comparison elementwise

In [26]:
x .> 12.0 # elementwise [array of bits is similar to array of bools]

6-element BitArray{1}:
 0
 0
 0
 1
 0
 1

In [27]:
x[x .> 12.0]

2-element Array{Float64,1}:
 43.0
 23.0

### multi-dimensional arrays

In [28]:
y = [1 3 1; 
    0 8 3]

2×3 Array{Int64,2}:
 1  3  1
 0  8  3

In [29]:
size(y) # two rows, three columns

(2, 3)

slicing e.g., 2nd column, all the rows

In [30]:
y[:, 2]

2-element Array{Int64,1}:
 3
 8

changing an element

In [31]:
y[1, 3] = 989
y

2×3 Array{Int64,2}:
 1  3  989
 0  8    3

### constructing an array
(without manually typing out its elements like `x = [2, 4, 6, 8, 10]`)

In [32]:
# (1) list comprehnsion (fast, beautiful)
x = [2.0 * i for i = 1:5] # think "what do I want in element i?"

# (2) pre-allocate memory, fill in (fast, takes a few lines)
x = zeros(Float64, 5) # construct a 5-element array with zeros
for i = 1:5
    x[i] = 2 * i
end

# (3) start with empty array, add values (slow)
x = Float64[]
for i = 1:5
    push!(x, 2 * i)
end
x

5-element Array{Float64,1}:
  2.0
  4.0
  6.0
  8.0
 10.0

special array constructors

In [33]:
y = zeros(Float64, 3, 6)
y = ones(Float64, 3, 6)
y = range(0.0, stop=1.0, length=5)
collect(y) # collect to actually build the array

5-element Array{Float64,1}:
 0.0 
 0.25
 0.5 
 0.75
 1.0 

### operations on arrays
precede with `.` to indicate element-wise

In [34]:
x = [0.0, 1.0, 2.0]
y = [5.0, 6.0, 7.0]

x .* y

3-element Array{Float64,1}:
  0.0
  6.0
 14.0

In [35]:
x .+ y

3-element Array{Float64,1}:
 5.0
 7.0
 9.0

In [36]:
sin.(x)

3-element Array{Float64,1}:
 0.0               
 0.8414709848078965
 0.9092974268256817

matrix multiplication (no `.` since no longer element-wise)

In [37]:
A = rand(3, 3)
A

3×3 Array{Float64,2}:
 0.317226  0.851315  0.674201
 0.504333  0.104395  0.988822
 0.410515  0.225576  0.73504 

In [38]:
A * x

3-element Array{Float64,1}:
 2.1997170402247566
 2.0820385799357735
 1.6956551166982665

## create your own data structure!

In [39]:
struct Molecule
    species::Symbol
    atoms::Array{Symbol}
end

molecule = Molecule(:methane, [:C, :H, :H, :H, :H])

Molecule(:methane, Symbol[:C, :H, :H, :H, :H])

In [40]:
molecule.species # access attributes

:methane

## functions

construction of a function $x \mapsto f(x)$

In [41]:
# (1) inline (if a short function)
f(x) = 2 * x + 3

# (2) expanded (if more code involved)
function f(x)
    # maybe tons of code here until we get to what we want to return
    return 2 * x + 3
end

# (3) anonomous functions https://docs.julialang.org/en/v1/manual/functions/#man-anonymous-functions-1
θ = x -> 2 * x + 3

f(2.0)

7.0

In [42]:
θ(2.0)

7.0

In [70]:
map(θ, [0.0, 1.0, 2.0]) # anonomous functions used for mapping, passing to other functions

3-element Array{Float64,1}:
 3.0
 5.0
 7.0

multiple arguments

In [43]:
f(x, y) = x + y
f(2.0, 3.0)

5.0

#### optional positional arguments

> In many cases, function arguments have sensible default values and therefore might not need to be passed explicitly in every call. [source](https://docs.julialang.org/en/v1/manual/functions/#Optional-Arguments-1)

say `b` is almost always 0.0. let's not force the user to pass this arugment, yet let's also allow some flexibility if the user wants to change `b` from the default 0.0

In [44]:
# constructor
f(x, m, b=0.0) = m * x + b

f(2.0, 1.0) # b assumed zero

2.0

In [45]:
f(2.0, 1.0, 23.0) # the third argument is assumed `b` if passed

25.0

#### optional keyword arguments

> Some functions need a large number of arguments, or have a large number of behaviors. Remembering how to call such functions can be difficult. Keyword arguments can make these complex interfaces easier to use and extend by allowing arguments to be identified by name instead of only by position. [source](https://docs.julialang.org/en/v1/manual/functions/#Keyword-Arguments-1)

In [46]:
# constructor
f(x, m; b=0.0) = m * x + b

f(2.0, 1.0) # b implicitly assumed to be 0.0

2.0

In [47]:
f(2.0, 1.0, b=23.0) # have to say explicitly you're passing `b`

25.0

#### type declaration
> The :: operator can be used to attach type annotations to expressions and variables in programs. There are two primary reasons to do this:

> * As an assertion to help confirm that your program works the way you expect,
> * To provide extra type information to the compiler, which can then improve performance in some cases
When appended to an expression computing a value, the :: operator is read as "is an instance of". It can be used anywhere to assert that the value of the expression on the left is an instance of the type on the right.
> [source](https://docs.julialang.org/en/v1/manual/types/index.html#Type-Declarations-1)

In [48]:
g(x::Float64) = 2.0 * x
g(2.0)

4.0

In [49]:
g(2) # we never defined g(x::Int), so it should rightfull fail

MethodError: MethodError: no method matching g(::Int64)
Closest candidates are:
  g(!Matched::Float64) at In[48]:1

a function of our custom data structure `Molecule`!

In [50]:
"""
calculate and return the molecular weight of the molecule passed on the basis of its `atoms` attribute.
"""
function molecular_wt(molecule::Molecule)
    mw = 0.0
    for atom in molecule.atoms
        mw += atomic_mass[atom]
    end
    return mw
end

molecular_wt(molecule)

16.041999999999998

safety: pass the wrong type, then you get an error

In [51]:
molecular_wt("not a molecule")

MethodError: MethodError: no method matching molecular_wt(::String)
Closest candidates are:
  molecular_wt(!Matched::Molecule) at In[50]:5

remember, put a `!` at the end of the function name to denote that it will modify its argument

In [52]:
y = [0, 5, 6]
function make_second_element_zero!(y::Array{Int64})
    y[2] = 0
end
make_second_element_zero!(y)
y

3-element Array{Int64,1}:
 0
 0
 6

## control flow
> a control flow statement is a statement, the execution of which results in a choice being made as to which of two or more paths a computer program wil follow - [Wikipedia](https://en.wikipedia.org/wiki/Control_flow)

let's redo our `molecular_wt` function to throw an informative error when we pass a molecule to it whose atoms are not present in our `atomic_mass` dictionary.

In [53]:
function molecular_wt(molecule::Molecule)
    mw = 0.0
    for atom in molecule.atoms
        # if this atom is not in our atomic_mass dictionary, throw an error
        if ! (atom in keys(atomic_mass))
            error("sorry, $atom is not in our atomic_mass dictionary.")
        end
        mw += atomic_mass[atom]
    end
    return mw
end
    
molecule = Molecule(:salt, [:Na, :Cl])

molecular_wt(molecule)

ErrorException: sorry, Na is not in our atomic_mass dictionary.

`break`, `continue`

In [54]:
x = [i for i = 1:5]

for (i, x_i) in enumerate(x)
    if x[i] == 4
        break # stop looping, don't proceed with next element in the iterator
    end
    
    println("x[$i] = $x_i")
end

x[1] = 1
x[2] = 2
x[3] = 3


In [55]:
for (i, x_i) in enumerate(x)
    if x[i] == 4
        continue # don't execute below this statement, continue onto the next element in the iterator
    end
    
    println("x[$i] = $x_i")
end

x[1] = 1
x[2] = 2
x[3] = 3
x[5] = 5


`&&` = and `||` = or

In [56]:
temperature = 55.0

temperature > 32.0 && temperature < 50.0

false

In [57]:
temperature > 32.0 || temperature < 50.0

true

cool way to assign variables

In [58]:
my_drink = (temperature > 65.0) ? "ice water" : "hot tea"

"hot tea"

## randomness, sampling
a uniform random number in $[0, 1]$

In [59]:
using Random
using StatsBase

In [60]:
rand()

0.8754678568735839

flipping a coin. did it land on tails?

In [61]:
landed_on_tails = rand() < 0.5

false

a Gaussian number

In [62]:
randn()

0.14923465370851044

randomly shuffle an array

In [63]:
x = [1, 2, 3, 4, 5, 6]
shuffle!(x)
x

6-element Array{Int64,1}:
 5
 6
 1
 4
 3
 2

randomly select 4 elements of the array, with/without replacement

In [64]:
sample(x, 4, replace=true)

4-element Array{Int64,1}:
 5
 1
 3
 2

In [65]:
sample(x, 4, replace=false)

4-element Array{Int64,1}:
 4
 5
 6
 1

simulate the weather when today's weather forcast is: 10% rain, 60% clouds, 30% sun

In [66]:
sample(["rainy", "cloudy", "sunny"], ProbabilityWeights([0.1, 0.6, 0.3]))

"cloudy"

### mutable vs immutable

In [67]:
struct Researcher
    institution::String
    nb_pubs::Int
end

publish_a_paper!(researcher::Researcher) = researcher.nb_pubs += 1 # won't work

cory = Researcher("OSU", 27)

publish_a_paper!(cory) # won't work

ErrorException: setfield! immutable struct of type Researcher cannot be changed

bummer! we can't change the attributes of a `Researcher` after we construct it... it's "immutable"! solution below.

In [68]:
mutable struct MutableResearcher
    institution::String
    nb_pubs::Int
end

publish_a_paper!(researcher::MutableResearcher) = researcher.nb_pubs += 1

cory = MutableResearcher("OSU", 27)

publish_a_paper!(cory)
cory

MutableResearcher("OSU", 28)