# the Julia programming language
<img src="https://i1.wp.com/www.numfocus.org/wp-content/uploads/2016/07/julia-logo-300.png?w=1080&ssl=1" alt="Julia logo" width="100"/>
So, why Julia?

* free, open-source
* high-level, thus easy to use
* expressive, read-like-a-book syntax
* fast (design choices allow just-in-time compiler to make optimizations, resulting in fast code)
* safety (offers optional type assertion)
* designed especially for scientific computing
* easy parallelization across cores
* multiple dispatch (we'll see later)

[link to official Julia website](https://julialang.org/) and [its documentation](https://docs.julialang.org/en/v1/)

[link to recent Nature article on Julia](https://www.nature.com/articles/d41586-019-02310-3)

another great resource to learn more Julia: [Julia express](http://bogumilkaminski.pl/files/julia_express.pdf)

## hello world, assignment

"an assignment statement sets and/or re-sets the value stored in the storage location(s) denoted by a variable name; in other words, it copies a value into the variable" - [Wikipedia](https://en.wikipedia.org/wiki/Assignment_(computer_science))

In [1]:
x = 5.3 # not "x equals 5.3" but, "assign x to be 5.3"

5.3

assignment is not the same as "equals"! read [here](https://en.wikipedia.org/wiki/Assignment_(computer_science)#Assignment_versus_equality).

In [2]:
x == 5.3

true

In [3]:
println("hello, world!") # "ln" is for "line" to creat a new line afterwards.

hello, world!


In [4]:
println("what's x? ", x)

what's x? 5.3


## types

`x` is represented on your computer using a chuck of memory consisting of 64 bits (bit = binary digit). It is represented in the [double-precision floating point format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).

<img src="https://upload.wikimedia.org/wikipedia/commons/a/a9/IEEE_754_Double_Floating_Point_Format.svg" alt="bits" width="500"/>

In [5]:
typeof(x)

Float64

In [6]:
y = 5
typeof(y)

Int64

In [7]:
my_name = "Cory"
typeof(my_name)

String

the `Symbol` is an [interned string](https://en.wikipedia.org/wiki/String_interning), which makes e.g. string comparison operations faster. 

For those interested:
A more nuanced view of the `Symbol` is [here](https://stackoverflow.com/questions/23480722/what-is-a-symbol-in-julia#) by the co-creator and core developer of Julia. The function `pointer_from_objref` in Julia allows you to see where in memory an object in Julia is stored. Experiment with a `Symbol` and `String` to illustrate that `Symbol`s are *interned* strings.

In [8]:
my_name = :Cory
typeof(my_name)

Symbol

In [9]:
typeof(true)
typeof(false)

Bool

## dictionaries
a collection of (key, value) pairs. e.g. key = element, value = atomic mass

constructing a dictionary

In [10]:
atomic_mass = Dict{Symbol, Float64}(:C => 12.01, :N => 14.0067, :O => 15.999, :H => 1.01)

Dict{Symbol,Float64} with 4 entries:
  :N => 14.0067
  :H => 1.01
  :O => 15.999
  :C => 12.01

querying a dictionary via passing the key, returning the value

In [11]:
atomic_mass[:C]

12.01

add a (key, value) pair to a dictionary

In [12]:
atomic_mass[:H] = 1.008
atomic_mass

Dict{Symbol,Float64} with 4 entries:
  :N => 14.0067
  :H => 1.008
  :O => 15.999
  :C => 12.01

iterate through a dictionary

In [13]:
for (element, mass) in atomic_mass # iterate over, unpack the (key, value) pairs
    print("the atomic mass of ")
    print(element)
    println(" is ", mass)
end

the atomic mass of N is 14.0067
the atomic mass of H is 1.008
the atomic mass of O is 15.999
the atomic mass of C is 12.01


### arrays

In [14]:
x = [6.3, 1.2, 8.2, 10.8] # column vector

4-element Array{Float64,1}:
  6.3
  1.2
  8.2
 10.8

changing an element

In [15]:
x[3] = 43.0
x

4-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8

iterating through an array

In [20]:
for i = 1:length(x)
    print("entry ")
    print(i)
    println(" is ", x[i])
end

println("entries are: ")
for x_i in x
    println("  ", x_i)
end

entry 1 is 6.3
entry 2 is 1.2
entry 3 is 43.0
entry 4 is 10.8
entries are: 
  6.3
  1.2
  43.0
  10.8


add an element to the end of the array

In [21]:
push!(x, 23.0) # exlamation means function will modify its argument
x

5-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8
 23.0

add an element to the beginning of the array

In [22]:
pushfirst!(x, 0.0)
x

6-element Array{Float64,1}:
  0.0
  6.3
  1.2
 43.0
 10.8
 23.0

#### slicing by indices (`Int64`s)

In [23]:
ids_i_want = [2, 6]

println("x = ", x)
println("x[ids_i_want] = ", x[ids_i_want])

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[ids_i_want] = [6.3, 23.0]


In [24]:
x[2:3]

2-element Array{Float64,1}:
 6.3
 1.2

In [25]:
x[2:end]

5-element Array{Float64,1}:
  6.3
  1.2
 43.0
 10.8
 23.0

#### slicing by boolean arrays

In [26]:
keep_entry = [true, false, false, false, false, true]

println("x = ", x)
println("x[keep_entry] = ", x[keep_entry])

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[keep_entry] = [0.0, 23.0]


slicing by boolean arrays is especially useful for querying

In [27]:
x > 12.0 # "is this vector greater than this number?" makes no sense.

MethodError: MethodError: no method matching isless(::Float64, ::Array{Float64,1})
Closest candidates are:
  isless(::Float64, !Matched::Float64) at float.jl:459
  isless(!Matched::Missing, ::Any) at missing.jl:66
  isless(::AbstractFloat, !Matched::AbstractFloat) at operators.jl:156
  ...

In [28]:
x .> 12.0 # elementwise [array of bits similar to array of bools

6-element BitArray{1}:
 0
 0
 0
 1
 0
 1

In [29]:
x[x .> 12.0]

2-element Array{Float64,1}:
 43.0
 23.0

multi-dimensional arrays

In [30]:
y = [1 3 1; 
    0 8 3]

2×3 Array{Int64,2}:
 1  3  1
 0  8  3

In [31]:
size(y) # two rows, three columns

(2, 3)

slicing e.g., 2nd column, all the rows

In [32]:
y[:, 2]

2-element Array{Int64,1}:
 3
 8

changing an element

In [33]:
y[1, 3] = 989
y

2×3 Array{Int64,2}:
 1  3  989
 0  8    3

three paradigms to construct an array

In [34]:
# (1) list comprehnsion (fast, beautiful)
x = [2.0 * i for i = 1:5] # think "what do I want in element i?"

# (2) pre-allocate memory, fill in (fast, takes a few lines)
x = zeros(Float64, 5) # construct a 5-element array with zeros
for i = 1:5
    x[i] = 2 * i
end

# (3) start with empty array, add values (slow)
x = Float64[]
for i = 1:5
    push!(x, 2 * i)
end
x

5-element Array{Float64,1}:
  2.0
  4.0
  6.0
  8.0
 10.0

special array constructors

In [35]:
y = zeros(Float64, 3, 6)
y = ones(Float64, 3, 6)
y = range(0.0, stop=1.0, length=5)
collect(y) # collect to actually build the array

5-element Array{Float64,1}:
 0.0 
 0.25
 0.5 
 0.75
 1.0 

element-wise operations: precede with `.` to indicate element-wise

In [44]:
x = [0.0, 1.0, 2.0]
y = [5.0, 6.0, 7.0]

x .* y

3-element Array{Float64,1}:
  0.0
  6.0
 14.0

In [45]:
x .+ y

3-element Array{Float64,1}:
 5.0
 7.0
 9.0

In [46]:
sin.(x)

3-element Array{Float64,1}:
 0.0               
 0.8414709848078965
 0.9092974268256817

matrix multiplication (no `.` since no longer element-wise)

In [47]:
A = rand(3, 3)
A

3×3 Array{Float64,2}:
 0.269557  0.355697  0.896255
 0.533244  0.443607  0.848735
 0.924767  0.780823  0.429421

In [48]:
A * x

3-element Array{Float64,1}:
 2.1482069108349675
 2.1410782242440467
 1.6396650584812795

### create your own data structure!

In [36]:
struct Molecule
    species::Symbol
    atoms::Array{Symbol}
end

molecule = Molecule(:methane, [:C, :H, :H, :H])

Molecule(:methane, Symbol[:C, :H, :H, :H])

In [37]:
molecule.species # access attributes

:methane

## control flow

In [38]:
# molecule = Molecule(:nitrogen, 14.00, [:N, :N])

if molecule.species == :methane
    println("whoah that is flammable!")
elseif molecule.species == :nitrogen
    println("no worries, not flammable.")
else
    println("nothing to say")
end

whoah that is flammable!


In [39]:
for i = 1:length(x)
    print("x[")
    print(i)
    println("] = ", x[i])
    if (x[i] > 5.0) && (x[i] < 7.0) # && means "and"
        println("eureka!")
    end
    if (x[i] < 3.0) || (x[i] > 8.0) # || means "or"
        println("extreme!")
    end
end

x[1] = 2.0
extreme!
x[2] = 4.0
x[3] = 6.0
eureka!
x[4] = 8.0
x[5] = 10.0
extreme!


## functions

construction of a function $x \mapsto f(x)$

In [51]:
# (1) inline (if a short function)
f(x) = 2 * x + 3

# (2) expanded (if more code involved)
function f(x)
    # maybe tons of code here until we get to what we want to return
    return 2 * x + 3
end

f(2.0)

7.0

multiple arguments

In [52]:
f(x, y) = x + y
f(2.0, 3.0)

5.0

optional arguments

In [53]:
f(x, m; b=0.0) = m * x + b
f(2.0, 1.0)

2.0

In [54]:
f(2.0, 1.0, b=23.0) # have to say explicitly you're passing `b`

25.0

In [55]:
f(x, m, b=0.0) = m * x + b
f(2.0, 1.0)

2.0

In [56]:
f(2.0, 1.0, 23.0) # the third argument is assumed `b` if passed

25.0

asserting type, for speed & safety

In [57]:
g(x::Float64) = 2.0 * x
g(2.0)

4.0

In [58]:
g(2)

MethodError: MethodError: no method matching g(::Int64)
Closest candidates are:
  g(!Matched::Float64) at In[57]:1

a function of our custom data structure `Molecule`!

In [59]:
function molecular_wt(molecule::Molecule)
    mw = 0.0
    for atom in molecule.atoms
        mw += atomic_mass[atom]
    end
    return mw
end

molecular_wt(molecule)

15.033999999999999

safety: pass the wrong type, then you get an error

In [61]:
molecular_wt("not a molecule")

MethodError: MethodError: no method matching molecular_wt(::String)
Closest candidates are:
  molecular_wt(!Matched::Molecule) at In[59]:2

remember, put a `!` at the end of the function name to denote that it will modify its argument

In [62]:
y = [0, 5, 6]
function make_second_element_zero!(y::Array{Int64})
    y[2] = 0
end
make_second_element_zero!(y)
y

3-element Array{Int64,1}:
 0
 0
 6

## randomness, sampling
a uniform random number in $[0, 1]$

In [63]:
using Random
using StatsBase

In [64]:
rand()

0.5365403341358983

flipping a coin. did it land on tails?

In [65]:
landed_on_tails = rand() < 0.5

true

a Gaussian number

In [66]:
randn()

-0.9180134018955154

randomly shuffle an array

In [67]:
x = [1, 2, 3, 4, 5, 6]
shuffle!(x)
x

6-element Array{Int64,1}:
 5
 1
 2
 4
 3
 6

randomly select 4 elements of the array, with/without replacement

In [69]:
sample(x, 4, replace=true)

4-element Array{Int64,1}:
 2
 1
 5
 5

In [70]:
sample(x, 4, replace=false)

4-element Array{Int64,1}:
 1
 2
 4
 5

simulate the weather when today's weather forcast is: 10% rain, 60% clouds, 30% sun

In [71]:
sample(["rainy", "cloudy", "sunny"], ProbabilityWeights([0.1, 0.6, 0.3]))

"cloudy"